### PR TITLE
feat: add price impact

### PR DESCRIPTION
**Pull request by adriexnet**
### What does this PR do?
Add the price impact for exchange 

### Steps to test
1. yarn
2. yarn start
3. navigate to http://localhost:3000/exchange
4. pick a pair and enter a valid amount 

#### CheckList
- [x] Follow proper Markdown format
- [x] The content is adequate
- [x] The content is available in both english and spanish
- [x] I Ran a spell check

### CODE REVIEW

**Review by xavier506 — APPROVED** [review]

**Comment by tetogomez** [comment]
@adriexnet let me know when this PR is done!

**Comment by adriexnet** [comment]
> @adriexnet let me know when this PR is done!

I just finished it, if it looks good for you go ahead and merge it

**Comment by xavier506** [comment]
@adriexnet  @murillojorge 

Can we adjust the line height so that the help text is not hidden behind the front layer ?

image

**Comment by adriexnet** [comment]
> @adriexnet @murillojorge
> 
> Can we adjust the line height so that the help text is not hidden behind the front layer ?
> 
> image

Fixed with my last commit

**Pull request merged**
